# Generated by Django 6.0.3 on 2026-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('slot_time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00')], max_length=5)),
                ('label', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('day', 'slot_time', 'id'),
                'constraints': [models.UniqueConstraint(fields=('day', 'slot_time'), name='core_availabilityblock_unique_slot')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('slot_time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00')], max_length=5)),
            ],
            options={
                'ordering': ('weekday', 'slot_time', 'id'),
                'constraints': [models.UniqueConstraint(fields=('weekday', 'slot_time'), name='core_weeklyavailability_unique_slot')],
            },
        ),
    ]
