# Generated by Django 6.0.3 on 2026-04-06 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availabilityblock_weeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyavailability',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
