# Generated by Django 6.0.3 on 2026-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_align_weeklyavailability_capacity_with_three'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('saturdays_non_working', models.BooleanField(default=True)),
                ('sundays_non_working', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'configuracion global de agenda',
                'verbose_name_plural': 'configuracion global de agenda',
            },
        ),
        migrations.CreateModel(
            name='ManualClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('local_holiday', 'Festivo local'), ('business_closure', 'Cierre del negocio'), ('personal', 'Asunto personal'), ('other', 'Otro')], default='other', max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('start_date', 'end_date', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='core_manualclosure_valid_range')],
            },
        ),
    ]
