# Generated by Django 6.0.3 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendasettings_manualclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'festivo oficial',
                'verbose_name_plural': 'festivos oficiales',
                'ordering': ('day', 'id'),
            },
        ),
    ]
