# Generated by Django 6.0.3 on 2026-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_officialholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialholiday',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('boe_national_sync', 'Sync BOE nacional')], db_index=True, default='manual', max_length=32),
        ),
    ]
