# Generated by Django 6.0.3 on 2026-04-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_officialholiday_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyavailability',
            name='core_weeklyavailability_unique_slot',
        ),
        migrations.DeleteModel(
            name='WeeklyAvailability',
        ),
    ]
