# Generated by Django 6.0.3 on 2026-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_weeklyavailability_core_weeklyavailability_unique_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_created_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_error_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_resolution_identifier',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_resolution_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_resolution_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_skipped_existing_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
