# Generated by Django 6.0.3 on 2026-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agendasettings_last_boe_sync_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agendasettings',
            name='last_boe_sync_failure_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
