# Generated by Django 6.0.3 on 2026-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agendasettings_last_boe_sync_failure_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendasettings',
            name='official_holidays_non_working',
            field=models.BooleanField(default=True),
        ),
    ]
