# Generated by Django 6.0.3 on 2026-04-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
