# Generated by Django 6.0.3 on 2026-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_service_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'datos del negocio',
                'verbose_name_plural': 'datos del negocio',
            },
        ),
    ]
