from django.urls import path

from .views import (
    AgendaSettingsView,
    AvailabilityBlockToggleView,
    AppEntryPointView,
    ArchivedClientListView,
    AppointmentCreateView,
    AppointmentUpdateView,
    BusinessSettingsView,
    CalendarUIValidationView,
    ClientArchiveView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    ClientReactivateView,
    ClientUpdateView,
    ManualClosureCreateView,
    ManualClosureDeleteView,
    ManualClosureUpdateView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceSettingsView,
    ServiceUpdateView,
    SettingsIndexView,
    UIValidationView,
    app_login_view,
    app_logout_view,
)


app_name = "core"

urlpatterns = [
    path("acceso/", app_login_view, name="login"),
    path("salir/", app_logout_view, name="logout"),
    path("app/", AppEntryPointView.as_view(), name="app_entrypoint"),
    path("app/settings/", SettingsIndexView.as_view(), name="settings_index"),
    path("app/settings/business/", BusinessSettingsView.as_view(), name="business_settings"),
    path("app/settings/agenda/", AgendaSettingsView.as_view(), name="agenda_settings"),
    path("app/settings/services/", ServiceSettingsView.as_view(), name="service_settings"),
    path("app/settings/services/new/", ServiceCreateView.as_view(), name="service_create"),
    path("app/settings/services/<int:pk>/edit/", ServiceUpdateView.as_view(), name="service_update"),
    path("app/settings/services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="service_delete"),
    path(
        "app/settings/agenda/closures/new/",
        ManualClosureCreateView.as_view(),
        name="manual_closure_create",
    ),
    path(
        "app/settings/agenda/closures/<int:pk>/edit/",
        ManualClosureUpdateView.as_view(),
        name="manual_closure_update",
    ),
    path(
        "app/settings/agenda/closures/<int:pk>/delete/",
        ManualClosureDeleteView.as_view(),
        name="manual_closure_delete",
    ),
    path("app/availability-blocks/toggle/", AvailabilityBlockToggleView.as_view(), name="availability_block_toggle"),
    path("app/appointments/new/", AppointmentCreateView.as_view(), name="appointment_create"),
    path("app/appointments/<int:pk>/edit/", AppointmentUpdateView.as_view(), name="appointment_update"),
    path("app/clients/", ClientListView.as_view(), name="client_list"),
    path("app/clients/archived/", ArchivedClientListView.as_view(), name="archived_client_list"),
    path("app/clients/archived/<int:pk>/reactivate/", ClientReactivateView.as_view(), name="client_reactivate"),
    path("app/clients/archived/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("app/clients/new/", ClientCreateView.as_view(), name="client_create"),
    path("app/clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("app/clients/<int:pk>/archive/", ClientArchiveView.as_view(), name="client_archive"),
    path("app/clients/<int:pk>/edit/", ClientUpdateView.as_view(), name="client_update"),
    path("app/ui/", UIValidationView.as_view(), name="ui_preview"),
    path("app/calendar-ui/", CalendarUIValidationView.as_view(), name="calendar_ui_preview"),
]
